export const locations = [
  { id: 1, name: "Chelmsford" },
  { id: 2, name: "Colchester" },
  { id: 3, name: "Southend-on-Sea" },
  { id: 4, name: "Basildon" },
  { id: 5, name: "Harlow" },
  { id: 6, name: "Brentwood" },
  { id: 7, name: "Billericay" },
  { id: 8, name: "Grays" },
  { id: 9, name: "Epping" },
  { id: 10, name: "Loughton" },
  { id: 11, name: "Witham" },
  { id: 12, name: "Maldon" },
  { id: 13, name: "Rayleigh" },
  { id: 14, name: "Wickford" },
  { id: 15, name: "Canvey Island" },
  { id: 16, name: "South Benfleet" },
  { id: 17, name: "Stanford-le-Hope" },
  { id: 18, name: "Tilbury" },
  { id: 19, name: "Clacton-on-Sea" },
  { id: 20, name: "Frinton-on-Sea" },
  { id: 21, name: "Walton-on-the-Naze" },
  { id: 22, name: "Castle Point" },
  { id: 23, name: "Epping Forest" },
  { id: 24, name: "Rochford" },
  { id: 25, name: "Tendring" },
  { id: 26, name: "Uttlesford" },
  { id: 27, name: "Romford" },
  { id: 28, name: "Ilford" },
  { id: 29, name: "Barking" },
  { id: 30, name: "Dagenham" },
  { id: 31, name: "Rainham" },
  { id: 32, name: "Upminster" },
  { id: 33, name: "Chadwell Heath" },
  { id: 34, name: "Chigwell" },
  { id: 35, name: "Woodford" },
  { id: 36, name: "Chingford" },
  { id: 37, name: "Walthamstow" },
  { id: 38, name: "Tottenham" },
  { id: 39, name: "Stratford" },
  { id: 40, name: "Hackney" },
  { id: 41, name: "Whitechapel" },
  { id: 42, name: "Mile End" },
  { id: 43, name: "Canary Wharf" },
  { id: 44, name: "Charlton" },
  { id: 45, name: "Greenwich" },
  { id: 46, name: "Dartford" },
  { id: 47, name: "Erith" },
  { id: 48, name: "Bexleyheath" },
  { id: 49, name: "Gravesend" },
];