import type { Metadata } from "next";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-wrap w-full">
          <div className="w-full">
            <Header />
          </div>

          {children}

          <div className="w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}